import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync, chmodSync, realpathSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { installMergeHook, hooksDir, HOOK_MARKER } from '../targets/worktree-reaper.mjs';

const git = (d, ...a) => execFileSync('git', a, { cwd: d, encoding: 'utf8' }).trim();
// On macOS /tmp and /var are symlinks and git resolves them; comparing raw paths never matches.
const real = (p) => realpathSync(p);

function repo() {
  const d = mkdtempSync(join(tmpdir(), 'rsc-hooks-'));
  git(d, 'init', '-q');
  git(d, 'config', 'user.email', 't@t');
  git(d, 'config', 'user.name', 't');
  git(d, 'commit', '-q', '--allow-empty', '-m', 'base');
  return d;
}

// The defect this file exists for: rsc wrote `.git/hooks/post-merge` unconditionally and
// doctor read the same path back, so on any repo with its own core.hooksPath — husky,
// lefthook, a committed .githooks dispatcher — the hook was installed where git does not
// look and the report said "armed". Found in a user's repo on 2026-09-18, on 2.0.1.
test('the hooks directory is the one git would use, not the one we assume', () => {
  const d = repo();
  assert.equal(real(hooksDir(d)), real(git(d, 'rev-parse', '--path-format=absolute', '--git-path', 'hooks')));
  git(d, 'config', 'core.hooksPath', '.githooks');
  assert.ok(hooksDir(d).endsWith('.githooks'), `a redirected hooksPath must be followed, got ${hooksDir(d)}`);
});

test('from a linked worktree it resolves the shared hooks directory, not a path that cannot exist', () => {
  const d = repo();
  git(d, 'worktree', 'add', '-q', join(d, 'wt'), '-b', 'tmp');
  // In a linked worktree `.git` is a FILE. The old code did mkdir('<wt>/.git/hooks') and got ENOTDIR.
  assert.ok(existsSync(join(d, 'wt', '.git')));
  assert.equal(real(hooksDir(join(d, 'wt'))), real(join(d, '.git', 'hooks')));
});

test('a worktree can arm the cleanup — it is the one feature that is used from worktrees', () => {
  const d = repo();
  git(d, 'worktree', 'add', '-q', join(d, 'wt'), '-b', 'tmp');
  const r = installMergeHook(join(d, 'wt'));
  assert.equal(r.installed, true, r.reason);
  assert.ok(readFileSync(join(d, '.git', 'hooks', 'post-merge'), 'utf8').includes(HOOK_MARKER));
});

// The design call: only write inside `.git/`. A committed `.githooks/` is the user's source
// tree, and `.husky/_` is regenerated by husky — writing to either means rsc editing someone
// else's repository to install a convenience of ours.
test('a hooks directory inside the work tree is reported, never written to', () => {
  const d = repo();
  git(d, 'config', 'core.hooksPath', '.githooks');
  mkdirSync(join(d, '.githooks'), { recursive: true });
  const r = installMergeHook(d);
  assert.equal(r.installed, false);
  assert.equal(r.state, 'unreachable');
  assert.ok(r.reason.includes('.githooks'), 'the reason must name the actual path, so it is actionable');
  assert.equal(existsSync(join(d, '.githooks', 'post-merge')), false, 'their tracked tree stays untouched');
  assert.equal(existsSync(join(d, '.git', 'hooks', 'post-merge')), false, 'and we do not write where git will not look');
});

test('an existing hook of theirs is still moved aside and chained when the directory IS ours', () => {
  const d = repo();
  const dir = join(d, '.git', 'hooks');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'post-merge'), '#!/bin/sh\necho theirs\n');
  chmodSync(join(dir, 'post-merge'), 0o755);
  const r = installMergeHook(d);
  assert.equal(r.installed, true);
  assert.equal(r.chained, true);
  assert.ok(readFileSync(join(dir, 'post-merge.rsc-local'), 'utf8').includes('echo theirs'));
});

// The worst half of the defect was not the misplaced file — it was the report. `doctor` read the
// same assumed path back and answered `armed` about a hook git would never run, and a check that
// confirms the one failure it exists to catch is worse than no check at all (P2).
test('doctor never calls a hook armed when git reads hooks from somewhere else', async () => {
  const { doctor } = await import('../scripts/doctor.js');
  const d = repo();
  git(d, 'config', 'core.hooksPath', '.githooks');
  mkdirSync(join(d, '.githooks'), { recursive: true });
  // Exactly the shape the user hit: our hook sitting in .git/hooks, inert.
  mkdirSync(join(d, '.git', 'hooks'), { recursive: true });
  writeFileSync(join(d, '.git', 'hooks', 'post-merge'), `#!/bin/sh\n${HOOK_MARKER}\n`);
  const report = doctor({ cwd: d, target: 'claude', home: join(d, '.home') });
  assert.notEqual(report.worktreeCleanup.state, 'armed', 'git would not run it, so we must not say it is armed');
  assert.equal(report.worktreeCleanup.state, 'unreachable');
  assert.ok(report.worktreeCleanup.action.includes('.githooks'), 'the report must name where git actually looks');
});

// And the recommendation must stop being circular: `repair` re-runs the same install, so telling
// someone to run it when the directory is not ours sends them round the loop again.
test('the unreachable report does not send them back to repair', async () => {
  const { doctor } = await import('../scripts/doctor.js');
  const d = repo();
  git(d, 'config', 'core.hooksPath', '.githooks');
  mkdirSync(join(d, '.githooks'), { recursive: true });
  const report = doctor({ cwd: d, target: 'claude', home: join(d, '.home') });
  assert.equal(report.worktreeCleanup.state, 'unreachable');
  assert.ok(!/rsc repair/.test(report.worktreeCleanup.action || ''));
});

test('a plain repo is still reported as armed once the hook is really there', async () => {
  const { doctor } = await import('../scripts/doctor.js');
  const d = repo();
  installMergeHook(d);
  assert.equal(doctor({ cwd: d, target: 'claude', home: join(d, '.home') }).worktreeCleanup.state, 'armed');
});

// Second half of the report: `applyInstall` called installMergeHook and threw the answer away, so
// a hook that could not arm was indistinguishable from one that did. It must be visible — and it
// must NOT fail the install: the harness is the point, the merge hook is a convenience on top.
test('an install whose hook cannot arm says so, and still installs', async () => {
  const { applyInstall } = await import('../scripts/install-apply.js');
  const d = repo();
  git(d, 'config', 'core.hooksPath', '.githooks');
  mkdirSync(join(d, '.githooks'), { recursive: true });
  const state = await applyInstall({ skillIds: ['orient'], target: 'claude', home: d, cwd: d });
  assert.ok(existsSync(join(d, '.claude', 'skills', 'orient', 'SKILL.md')), 'the harness still installs');
  assert.equal(state.mergeHook?.installed, false);
  assert.equal(state.mergeHook?.state, 'unreachable');
});

test('and an install that arms it normally reports that too', async () => {
  const { applyInstall } = await import('../scripts/install-apply.js');
  const d = repo();
  const state = await applyInstall({ skillIds: ['orient'], target: 'claude', home: d, cwd: d });
  assert.equal(state.mergeHook?.installed, true);
});
