import { existsSync, lstatSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

// ─────────────────────────────────────────────────────────────────────────────
// La constitución como BORRADOR.
//
// El suelo del arnés exige `02-DOCS/wiki/sdd/constitution.md` cuando el plan elige SDD, y sólo una
// fase agéntica la escribía. Así que una instalación no interactiva de software complejo —terminal,
// CI, nadie con un agente delante— terminaba en RSC_ONBOARDING_INCOMPLETE: medio instalada. En la
// prueba de campo una sesión entera ($3.59, 67 turnos) se gastó sólo en escribirla.
//
// Decisión del PO (2026-10-07): el onboarding escribe un BORRADOR y no falla. El borrador lleva
// `status: draft`, los encabezados reales de la plantilla de la fase `constitution`, y sólo los
// hechos que el onboarding conoce — objetivo, tipo, alcance, flujo, evidencia de stack. Ningún
// principio: ratificar es de la fase `constitution`, con el usuario delante (P4). El suelo lo acepta
// porque sólo mira existencia; la cadena SDD lo detecta por `status: draft` y lo completa antes del
// primer spec; `doctor` lo lista como pendiente, nunca como fallo.

export const CONSTITUTION_PATH = '02-DOCS/wiki/sdd/constitution.md';
export const DRAFT_MARK = 'borrador — complétalo con la fase `constitution` antes del primer SDD';

const WORKFLOW_FACT = {
  branches: 'branches closed with a pull request; the default branch is closed to direct work',
  main: 'straight on the default branch',
};

// El objetivo es texto del usuario y va a un documento que leerá un agente: una línea, acotada.
const oneLine = (value, limit = 200) => String(value ?? '').replace(/[\u0000-\u001f\u007f]+/g, ' ')
  .replace(/\s+/g, ' ').trim().slice(0, limit);

/** Puro: el texto del borrador a partir del plan aceptado. Sin reloj ni disco, salvo lo que se le pase. */
export function renderConstitutionDraft(plan, { project = 'Project', date = new Date() } = {}) {
  const record = plan?.record || {};
  const evidence = plan?.evidence || {};
  const stacks = (evidence.stacks || []).map((s) => oneLine(s, 40)).filter(Boolean);
  const manifests = (evidence.signals || []).filter((s) => String(s).startsWith('manifest:'))
    .map((s) => oneLine(String(s).slice('manifest:'.length), 60));
  const day = date.toISOString().slice(0, 10);
  const name = oneLine(project, 80) || 'Project';
  const stackLine = stacks.length
    ? `Detected at install: ${stacks.join(', ')}${manifests.length ? ` (from ${manifests.join(', ')})` : ''}. Not ratified yet.`
    : 'No stack evidence was detected at install. To be decided in the `constitution` phase.';
  const workflow = WORKFLOW_FACT[record.workflow];
  const pending = '_Pending — to be completed in the `constitution` phase._';
  return `---
type: constitution
title: ${name} — Constitution
description: Draft written by rsc onboard from the accepted plan; not ratified.
tags: [sdd, constitution]
timestamp: ${date.toISOString().replace(/\.\d{3}Z$/, 'Z')}
topic: sdd
status: draft
version: draft
---

# ${name} — Constitution

> **${DRAFT_MARK}.**
> Draft: complete it with the \`constitution\` phase before the first SDD feature. It holds only what
> onboarding knew; it ratifies no principle. Ratifying it removes \`status: draft\` and starts at v1.0.0.

## Known facts (from onboarding)

- Goal: ${oneLine(record.goal)}
- Project kind: ${oneLine(record.projectKind, 40)}${record.softwareScope ? ` · software scope: ${oneLine(record.softwareScope, 40)}` : ''}
${workflow ? `- How code changes land: ${workflow} (\`--workflow ${record.workflow}\`).\n` : ''}- Stack evidence: ${stackLine}

## 1. Stack canon

${stackLine}

## 2. Quality bar

${pending}

## 3. Conventions

${pending}

## 4. Branching & shipping

${workflow ? `Chosen at install: ${workflow}. ` : ''}${pending}

## 5. Security & privacy floor

${pending}

## 6. UX / accessibility floor (if there is a UI)

${pending}

## 7. Performance budgets (where they matter)

${pending}

## 8. Knowledge & decisions

${pending}

## Definition of Done (the merge bar \`verify\` runs against)

${pending}

## Amendment log (append-only)

| Date | Version | Change | Why |
|------|---------|--------|-----|
| ${day} | draft | Draft generated by \`rsc onboard\`. | The SDD floor needs a constitution; ratification is the \`constitution\` phase's. |
`;
}

/** ¿La constitución existe y está en borrador? Sólo lee el frontmatter; ilegible ⇒ no es borrador. */
export function constitutionIsDraft(cwd = process.cwd()) {
  const path = join(cwd, CONSTITUTION_PATH);
  try {
    if (!existsSync(path) || !lstatSync(path).isFile()) return false;
    const text = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
    const block = /^---\n([\s\S]*?)\n---(\n|$)/.exec(text);
    return Boolean(block && /^status:\s*["']?draft["']?\s*$/m.test(block[1]));
  } catch {
    return false;
  }
}

const isLink = (path) => { try { return lstatSync(path).isSymbolicLink(); } catch { return false; } };

/**
 * Escribe el borrador si el plan exige la constitución y no hay ninguna. Nunca sobrescribe: ni una
 * ratificada ni un borrador que el usuario ya empezó. Un enlace (aunque cuelgue) cuenta como
 * existente, y `wx` cierra la carrera entre comprobar y escribir.
 */
export function ensureConstitutionDraft(cwd, plan, { now = new Date() } = {}) {
  if (!(plan?.floorPaths || []).includes(CONSTITUTION_PATH)) return { created: false };
  // Sin importar `onboarding-apply.js` (doctor lee este módulo y no debe arrastrar el instalador):
  // un directorio intermedio que sea enlace podría sacar la escritura de la raíz, y git versiona los
  // enlaces, así que el vector viaja en un clone. Más estricto que la guarda general: no se sigue.
  let cursor = cwd;
  for (const segment of ['02-DOCS', 'wiki', 'sdd']) {
    cursor = join(cursor, segment);
    if (existsSync(cursor) || isLink(cursor)) {
      if (lstatSync(cursor).isSymbolicLink()) throw new Error(`RSC_ROOT_AMBIGUOUS: ${CONSTITUTION_PATH} would be written through a symlink`);
    }
  }
  const target = join(cwd, CONSTITUTION_PATH);
  let present = false;
  try { lstatSync(target); present = true; } catch { /* ausente */ }
  if (present) return { created: false };
  mkdirSync(join(cwd, '02-DOCS', 'wiki', 'sdd'), { recursive: true });
  try {
    writeFileSync(target, renderConstitutionDraft(plan, { project: basename(cwd), date: now }), { flag: 'wx' });
  } catch (error) {
    if (error.code === 'EEXIST') return { created: false };
    throw error;
  }
  return { created: true };
}
